Split function into files + Change getopts > getoptions

diff --git a/.asset/functions/newplugin b/.asset/functions/newplugin
--- a/.asset/functions/newplugin
+++ b/.asset/functions/newplugin
@@ -1,4 +1,110 @@
-#!/usr/bin/env bash
+
+#Create a new plugin using tool_pluginskel
+mpdk_newplugin() {
+    #Sanity check
+    #Check if the container is running
+    mpdk_requirerunning
+    #Get the dialog ENV if present use "dialog" as fallback
+    dialog=${DIALOG:-dialog}
+    #Output redirection required for use "dialog"
+    output="3>&1 1>&2 2>&3 3>&-"   
+
+    #Show all the form
+    type="$(eval "$dialog $PLUGIN_TYPE_DIALOG $output")";
+    shortname="$(eval "$dialog $PLUGIN_COMPONENT_NAME_DIALOG $output")";
+    name="$(eval "$dialog  $PLUGIN_DISPLAY_NAME_DIALOG $output")";
+    features="$(eval "$dialog $PLUGIN_FEATURES_DIALOG $output")";
+    privacy="$(eval "$dialog $PLUGIN_PRIVACY_DIALOG $output")";
+    minversion="$(eval "$dialog $PLUGIN_REQUIRES_VERSION_DIALOG $output")";
+    release="$(eval "$dialog $PLUGIN_RELEASE_DIALOG $output")";
+    version="$(eval "$dialog $PLUGIN_VERSION_DIALOG $output")";
+    maturity="$(eval "$dialog $PLUGIN_MATURITY_DIALOG $output")";
+    editmanualy="$(eval "$dialog $PLUGIN_CREATE_DIALOG $output")";
+    
+
+    #Create "features" yaml part
+    feautes_string="features:\n"
+    recipename="$type"_"$shortname";
+    for f in $features; do
+        feautes_string+="    $f: true \n"
+    done
+
+    #Create main yaml part (indentation is relevant) 
+    yaml="
+#Generated by mpdk script for tool_pluginskel
+copyright: '$COPYRIGHT_STRING'
+component: '$recipename'
+release: $release
+version: $version
+requires: '$minversion'
+maturity: $maturity
+name: '$name'\n""$feautes_string"
+
+    #Create privacy yaml part
+    if [ "$privacy" -eq 1 ]; then
+        yaml+="privacy:\n    haspersonaldata: true\n"
+    fi
+    #If the user choose to continue editing the file manually, output it and exit
+    if [ "$editmanualy" -eq 1 ]; then
+        clear
+        printf "\nCopy your recipe:"
+        printf "\n\n$yaml\n\n"
+        exit
+    fi
+
+    #Ask the user if to create also a git repo
+    git="$(eval "$dialog $PLUGIN_GIT_DIALOG $output")";
+    grunt="$(eval "$dialog $PLUGIN_GRUNT_DIALOG $output")";
+    clear
+    #Create the yaml file
+    printf "$yaml" > "$ASSET"/recipe/"$recipename".yaml
+    #Copy the file in the moodle dr, so it's visible inside the conatiner
+    cp "$ASSET"/recipe/"$recipename".yaml "$IROOT"/"$recipename".yaml
+    #Execute tool_pluginskel generate.php
+    result="$(mpdk_sh php admin/tool/pluginskel/cli/generate.php --target-moodle=/var/www/html /var/www/html/"$recipename".yaml)"
+    #Delete the file inside moodle, as we don't want to keep it here
+    rm "$IROOT"/"$recipename".yaml
+    #Get the new plugin directory
+    relpath="$(echo "$result" | sed "s+.*\/var\/www\/html++g")"
+  
+    [ -z "$relpath" ] && printf "\nSomething went wrong" && exit
+    [ "${relpath:${#relpath}-1:1}" != '/' ] && relpath+='/'
+    [ "${relpath:0:1}" = '/' ] && relpath="${relpath:1:${#relpath}}"
+    plugindir=$IROOT"$relpath"
+    #Get the warning and error from tool_pluginskel (warning are like useful advice)
+    result="$(echo "$result" | sed "s+\[.\{32\}\].tool_pluginskel\.[A-Z]*:.+\n+g" | cut -f 1 -d "[")"
+    #Check if we have a directory, otherwise something went wrong
+    if [ -z "$plugindir" ];then 
+        printf '\nAn error as occurred! Please try again...'
+        exit
+    fi
+    #Create the git repository if requested by the user 
+    if [ $git -eq 1 ]; then
+        cd "$plugindir" || ( printf "\nSomething went wrong..." && exit )
+        wget --quiet -O "$plugindir"/.gitignore "https://www.toptal.com/developers/gitignore/api/phpunit,phpstorm+all,macos,windows,linux,eclipse,visualstudiocode,netbeans,python,node,grunt,sublimetext,phpcodesniffer,composer" & mpdk_spinner $!
+        git init --quiet
+        git add .
+        #Make the first commit
+        git commit --quiet -m "Initial commit, plugin just generated with mpdk and pluginskel (auto)" 
+    fi
+    #Add a gruntfile
+    clear
+    if [ $grunt -eq 1 ];then
+        printf '{\n    "name": "moodle-'$recipename'",\n    "private": true}' > "$plugindir"/package.json
+        mpdk_sh "cd $relpath && npm install --save-dev grunt grunt-contrib-less grunt-contrib-watch grunt-load-gruntfile 1>/dev/null" & mpdk_spinner $!
+        #Adjust the reference to the global gruntfile
+        gruntpath="$(echo $relpath | sed -r "s#[A-Za-z0-9-]+#\.\.#g")"Gruntfile.js
+        cat "$ASSET"/gruntfile | sed "s+%relpath%+$gruntpath+g" > "$plugindir"/Gruntfile.js
+    fi
+    #Save the entry in myplugins file
+    mpdk_addplugin "$recipename" "$relpath"
+    #Print the warnign and error from tool_pluginskel to the user
+    
+    printf "\n\n$result\n";
+    printf "\nYour plugin is ready inside: $plugindir, happy coding!\n"
+}
+
+
 height=15
 width=60
 listheight=16
